// Auto-generated by build-renderer.js — do not edit manually.
// Regenerated on every `npm run build`. Commit this file.
export const SPECGEN_HASH = '1179cd3a46fee9fca3519e477005dfdd77f14f5caddd1b3c369e25f619b0eb37';
export const SPECGEN_VERSION = '0.0.20260602';
