// Auto-generated by build-renderer.js — do not edit manually.
// Regenerated on every `npm run build`. Commit this file.
export const SPECGEN_HASH = '72a8046a673b04eda739ca0393ea46f840fd8fbc76a0a223ae015ddbd1d64325';
export const SPECGEN_VERSION = '0.0.20260602';
